spring:
  datasource:
    url: jdbc:mysql://localhost:3307/muban?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: "199967fcx"
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true