#AAA23 改变默认的静态资源访问前缀以及路径
#spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: classpath:/haha/

#step3 修改配置项
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/muban?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: "199967fcx"
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3

#配置mybatis规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml #全局配置文件位置，可以不写，而且和下面的全局配置冲突
  mapper-locations: classpath:mybatis/mapper/*.xml #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true